// src/routes/(signin)/redirect/+page.svelte
<script>
	import { browser } from '$app/environment';
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import PocketBase from 'pocketbase';

	const db = new PocketBase(import.meta.env.VITE_POCKETBASE_URL);

	if (browser) {
		const authProvider = JSON.parse(window.localStorage.getItem('provider') || '{}');
		localStorage.removeItem('provider');
		if (!authProvider) {
			goto('/');
		} else {
			db.users
				.authViaOAuth2(
					authProvider.name,
					$page.url.searchParams.get('code') || '',
					authProvider.codeVerifier,
					import.meta.env.VITE_REDIRECT_URL,
				)
				.then((signInRes) => {
					db.records
						.update('profiles', signInRes.user.profile?.id || '', {
							name: signInRes.meta.name,
							avatar: signInRes.meta.avatarUrl,
						})
						.then(() => {
							goto('/');
						});
				});
		}
	}
</script>

<svelte:head>
	<title>Redirect</title>
	<meta name="description" content="Svelte demo app" />
</svelte:head>

<div>Loading...</div>

// app/redirect/page.tsx
'use client';

import { useRouter } from 'next/navigation';
import PocketBase from 'pocketbase';
import { useEffect } from 'react';

const db = new PocketBase('http://localhost:8090');

export default function RedirectPage({ searchParams }: any) {
  const router = useRouter();

  if (typeof window === 'undefined') {
    return null;
  }

  var localStorageProvider = localStorage.getItem('provider');

  if (!localStorageProvider) {
    return router.push('/');
  }

  const authProvider = JSON.parse(localStorageProvider);

  if (!authProvider.name || !authProvider.codeVerifier || !searchParams.code) {
    return router.push('/');
  }

  const loginUser = async () => {
    const loginRes = await db.users.authViaOAuth2(
      authProvider.name,
      searchParams.code,
      authProvider.codeVerifier,
      'http://localhost:3000/redirect',
    );

    const test = await db.records.update('profiles', loginRes.user.profile?.id || '', {
      name: loginRes.meta.name,
      avatar: loginRes.meta.avatarUrl,
    });
  };

  loginUser().then(() => {
    router.push('/');
  });

  return <div>Loading...</div>;
}
